"""
Uploading the student's own documents — the transcript behind the offer.

The offer letter is generated by us; these files are the ones that justify it,
and until now they never left this machine: ``lead_documents`` had no CRM
columns and nothing uploaded them. The admissions team could see an offer
without ever seeing what supported it.

They share the chunked transfer with the offer letter (same three calls, same
never-retry-on-complete rule) and differ in two places that these tests pin:
the document type comes from a mapping onto the org's own vocabulary, and the
bookkeeping lives on the document row rather than the offer row.
"""

from __future__ import annotations

import httpx
import pytest

from app.crm import documents as docs_mod
from app.crm import identity as ident
from app.crm.client import CrmClient

PDF = b"%PDF-1.4\n" + (b"x" * 3000) + b"\n%%EOF\n"
DOC_ID = "c852f7d9-1234-5678-9abc-def012345678"
USER = "0o6T100000000pdIAA"
UPLOAD_ID = "3f1a9e0c-1b2d-4c3e-8f90-abcdef012345"


@pytest.fixture
def crm_on(override_settings):
    override_settings(
        CRM_ENABLED=True,
        CRM_DOCUMENT_UPLOAD_ENABLED=True,
        CRM_OFFER_DOCUMENT_SOURCE="Internal Upload",
        CRM_UPLOAD_CHUNK_BYTES=1024 * 1024,
        CRM_UPLOAD_TIMEOUT_S=30.0,
        CRM_MAX_RETRIES=0,
    )


@pytest.fixture
def store(monkeypatch):
    """The four accessors the student-document path touches."""
    state = {
        "user_id": USER,
        "application_no": "APP-28B9A16C28",
        "doc_state": {"document_id": "", "status": "", "uploaded_at": None},
        "recorded": [],
        "cleared": [],
        "application_pushes": [],
    }

    async def get_lead_crm_user_id(lead_id):
        return state["user_id"]

    async def get_lead_crm_application_no(lead_id):
        return state["application_no"]

    async def set_lead_crm_application_no(lead_id, value):
        state["application_no"] = value or ""
        state["application_pushes"].append(value)
        return True

    async def get_document_crm_upload(doc_id):
        return state["doc_state"]

    async def set_document_crm_upload(doc_id, *, document_id="", status=""):
        state["recorded"].append({"document_id": document_id, "status": status})
        if document_id:
            state["doc_state"] = {
                "document_id": document_id, "status": status, "uploaded_at": None
            }
        return True

    monkeypatch.setattr("app.leads.models.get_lead_crm_user_id", get_lead_crm_user_id)
    monkeypatch.setattr("app.leads.models.get_lead_crm_application_no", get_lead_crm_application_no)
    monkeypatch.setattr("app.leads.models.set_lead_crm_application_no", set_lead_crm_application_no)
    monkeypatch.setattr("app.offers.models.get_document_crm_upload", get_document_crm_upload)
    monkeypatch.setattr("app.offers.models.set_document_crm_upload", set_document_crm_upload)
    return state


@pytest.fixture
def client(monkeypatch):
    sent: list[dict] = []
    state = {"responses": []}

    def handler(request: httpx.Request) -> httpx.Response:
        import json
        sent.append({
            "path": request.url.path,
            "content_type": request.headers.get("content-type", ""),
            "body": request.content,
            "form": json.loads(request.content) if request.content[:1] == b"{" else {},
        })
        idx = min(len(sent) - 1, len(state["responses"]) - 1)
        return state["responses"][idx] if state["responses"] else httpx.Response(200, json={})

    c = CrmClient("http://crm.test", transport=httpx.MockTransport(handler), max_retries=0)
    monkeypatch.setattr("app.crm.documents.get_client", lambda: c)
    return sent, state


def scripted(*responses):
    return list(responses)


def upload(doc_id=DOC_ID, path="/tmp/x.pdf", doc_type="transcript", name="RAG.md.pdf"):
    return docs_mod.upload_student_document(
        lead_id="lead-1", doc_id=doc_id, file_path=path, doc_type=doc_type,
        original_name=name,
    )


@pytest.fixture
def pdf(tmp_path):
    p = tmp_path / "RAG.md.pdf"
    p.write_bytes(PDF)
    return str(p)


def ok_listing() -> httpx.Response:
    return httpx.Response(200, json=[])


def init_ok() -> httpx.Response:
    return httpx.Response(200, json={"upload_id": UPLOAD_ID, "total_chunks": 1,
                                     "status": "initiated"})


def chunk_ok() -> httpx.Response:
    return httpx.Response(200, json={"upload_id": UPLOAD_ID, "chunk_number": 1,
                                     "received_chunks": 1, "total_chunks": 1})


def complete_ok(document_id="068T100000cVgi7IAC") -> httpx.Response:
    return httpx.Response(200, json={"upload_id": UPLOAD_ID, "status": "completed",
                                     "document": {"document_id": document_id,
                                                  "file_name": "x.pdf"}})


# ── the happy path ───────────────────────────────────────────────────────────

@pytest.mark.anyio
async def test_a_transcript_reaches_the_crm(crm_on, client, store, pdf):
    sent, state = client
    state["responses"] = scripted(ok_listing(), init_ok(), chunk_ok(), complete_ok())

    assert await upload(path=pdf) == "068T100000cVgi7IAC"

    paths = [s["path"] for s in sent]
    assert paths[0] == "/admissions/APP-28B9A16C28/documents"
    assert paths[1] == "/admissions/APP-28B9A16C28/documents/uploads"
    assert paths[-1].endswith("/complete")
    assert store["recorded"][-1] == {"document_id": "068T100000cVgi7IAC",
                                     "status": "uploaded"}


def init_fields(request_body: bytes) -> dict:
    """
    The init call's form fields.

    It is a fields-only request, so httpx encodes it as urlencoded (spaces become
    "+"), not multipart — parsing it is the only way to compare values.
    """
    return dict(httpx.QueryParams(request_body.decode()))


@pytest.mark.anyio
async def test_the_transcript_is_filed_as_an_academic_transcript(crm_on, client, store, pdf):
    """The org's vocabulary, not ours — `transcript` is not a value it accepts."""
    sent, state = client
    state["responses"] = scripted(ok_listing(), init_ok(), chunk_ok(), complete_ok())

    await upload(path=pdf, doc_type="transcript")

    fields = init_fields(sent[1]["body"])
    assert fields["document_type"] == "Academic Transcript"
    assert fields["source"] == "Internal Upload"


@pytest.mark.anyio
async def test_an_id_proof_is_filed_as_an_id_document(crm_on, client, store, pdf):
    sent, state = client
    state["responses"] = scripted(ok_listing(), init_ok(), chunk_ok(), complete_ok())

    await upload(path=pdf, doc_type="id_proof")

    assert init_fields(sent[1]["body"])["document_type"] == "ID Document"


@pytest.mark.anyio
async def test_the_file_name_keeps_the_original_and_stays_unique(crm_on, client, store, pdf):
    """
    The admissions team reads these names, so the student's own file name is
    kept — prefixed with the row id so a re-upload of a *different* file is not
    mistaken for the same one.
    """
    sent, state = client
    state["responses"] = scripted(ok_listing(), init_ok(), chunk_ok(), complete_ok())

    await upload(path=pdf)

    init = sent[1]["body"].decode()
    assert "C852F7D9_RAG.md.pdf" in init


@pytest.mark.anyio
async def test_a_large_document_is_chunked(crm_on, client, store, tmp_path, override_settings):
    override_settings(CRM_UPLOAD_CHUNK_BYTES=1024)
    big = tmp_path / "big.pdf"
    big.write_bytes(b"%PDF" + b"y" * 5000)
    sent, state = client
    state["responses"] = scripted(ok_listing(), init_ok(), chunk_ok(), chunk_ok(),
                                  chunk_ok(), chunk_ok(), chunk_ok(), chunk_ok(), complete_ok())

    await upload(path=str(big))

    chunks = [s for s in sent if s["path"].endswith("/chunks")]
    assert len(chunks) == 5, "5004 bytes in 1KB chunks"
    # The first chunk starts with the file's own bytes (the header is 4 bytes,
    # so 1020 of the remaining 1024 are payload), and the last chunk is the tail.
    assert b"%PDF" in chunks[0]["body"]
    assert b"y" * 1000 in chunks[0]["body"]
    assert b"y" in chunks[-1]["body"]


# ── the guards ───────────────────────────────────────────────────────────────

@pytest.mark.anyio
async def test_an_already_uploaded_document_is_not_sent_again(crm_on, client, store, pdf):
    sent, _ = client
    store["doc_state"] = {"document_id": "068OLD", "status": "uploaded", "uploaded_at": None}

    assert await upload(path=pdf) == "068OLD"
    assert sent == [], "the recorded id short-circuits everything"


@pytest.mark.anyio
async def test_a_lead_with_no_crm_link_is_skipped(crm_on, client, store, pdf):
    sent, _ = client
    store["user_id"] = ""

    assert await upload(path=pdf) == ""
    assert sent == []


@pytest.mark.anyio
async def test_the_upload_can_be_switched_off_while_the_offer_upload_stays_on(
    client, store, pdf, override_settings
):
    """
    The two switches are independent by design: transcripts carry grades and
    identity documents, and an operator may want the generated offer letter in
    the CRM while these stay here pending sign-off.
    """
    override_settings(CRM_ENABLED=True, CRM_OFFER_UPLOAD_ENABLED=True,
                      CRM_DOCUMENT_UPLOAD_ENABLED=False)
    sent, _ = client

    assert await upload(path=pdf) == ""
    assert sent == []


@pytest.mark.anyio
async def test_a_missing_file_is_not_uploaded(crm_on, client, store, tmp_path):
    """The file may have been removed between the row being written and the upload."""
    sent, _ = client

    assert await upload(path=str(tmp_path / "gone.pdf")) == ""
    assert sent == []


@pytest.mark.anyio
async def test_a_duplicate_is_adopted_not_re_uploaded(crm_on, client, store, pdf):
    """
    Crash recovery: a previous attempt created the document but never recorded
    it. Matching on our deterministic file name finds it.
    """
    sent, state = client
    state["responses"] = scripted(httpx.Response(200, json=[
        {"document_id": "068EXISTING", "file_name": "C852F7D9_RAG.md.pdf",
         "document_type": "Academic Transcript"},
    ]))

    assert await upload(path=pdf) == "068EXISTING"
    assert len(sent) == 1, "only the listing call — no second copy created"
    assert store["recorded"][-1]["status"] == "uploaded"


@pytest.mark.anyio
async def test_an_ambiguous_complete_is_recorded_as_unknown(crm_on, client, store, pdf):
    """A 500 on complete may mean the document exists; it must never be retried."""
    sent, state = client
    state["responses"] = scripted(ok_listing(), init_ok(), chunk_ok(),
                                  httpx.Response(500, json={"detail": "boom"}))

    assert await upload(path=pdf) == ""
    completes = [s for s in sent if s["path"].endswith("/complete")]
    assert len(completes) == 1, "not retried — that could duplicate the document"
    assert store["recorded"][-1]["status"] == "unknown"


@pytest.mark.anyio
async def test_an_unavailable_listing_skips_rather_than_risking_a_duplicate(
    crm_on, client, store, pdf
):
    sent, state = client
    state["responses"] = scripted(httpx.Response(500, json={"detail": "listing down"}))

    assert await upload(path=pdf) == ""
    assert not any(s["path"].endswith("/uploads") for s in sent)


# ── the mapping itself ───────────────────────────────────────────────────────

def test_document_types_map_onto_the_org_vocabulary():
    assert ident.map_document_type("transcript") == "Academic Transcript"
    assert ident.map_document_type("id_proof") == "ID Document"
    assert ident.map_document_type("other") == "Other"


def test_an_unrecognised_document_type_falls_back_rather_than_failing():
    """The document is real; filing it under a general label beats losing it."""
    assert ident.map_document_type("something-new") == "Other"
    assert ident.map_document_type("") == "Other"
    assert ident.map_document_type(None) == "Other"


def test_every_mapped_value_is_a_value_the_org_accepts():
    """
    The picklist is restricted — the API validates nothing, so a typo here
    becomes a 500 at upload time. These are the values read from the org.
    """
    accepted = {
        "Academic Transcript", "Resume", "Financial Document", "ID Document",
        "Admission Call Recording", "Chatbot Conversation Record", "Test Score",
        "Recommendation Letter", "Other", "10th Marksheet", "12th Marksheet",
        "Diploma Marksheet", "Bachelor's Last-Semester Result", "IELTS Score",
        "Diploma Last-Semester Result",
    }
    for value in ident.DOCUMENT_TYPE_MAP.values():
        assert value in accepted, f"{value!r} is not in the org's Document_Type__c"
