"""
Machine Profile — hardware detection, config sizing, .env management
=====================================================================
Pre-deployment machine-adaptive configuration. Detects the machine
(RAM, VRAM, CPU cores, GPU, cloud vs local), picks a sizing tier, and
merges machine-derived values into a clearly-marked block in .env.
Never touches secrets or manual overrides outside the block.

Stdlib-only by design: scripts/predeploy.py runs before the venv
exists, and app/platform.py's detect_compute_device() raises without
torch — so this module uses subprocess probes (nvidia-smi, sysctl)
and os.sysconf instead. psutil is used opportunistically when present.

Usage:
    from app.hardware_profile import detect_hardware, select_tier, apply_profile

    hw = detect_hardware()          # machine facts
    tier = select_tier(hw)          # sizing recommendation
    result = apply_profile(".env", tier)   # merge block into .env
    drift = check_drift()           # startup self-check
"""

import hashlib
import json
import os
import platform as _platform
import re
import socket
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# ── Constants ─────────────────────────────────────────────────────────

PROFILE_MARKER_OPEN = "# === MACHINE PROFILE — auto-generated by scripts/predeploy.py (do not edit) ==="
PROFILE_MARKER_CLOSE = "# === END MACHINE PROFILE ==="

#: Keys managed inside the block, in canonical order. Everything else in
#: .env is never touched.
MANAGED_KEYS = [
    "LLM_PROVIDER",
    "MLX_MODEL",
    "MLX_EMBED_MODEL",
    "OLLAMA_MODEL",
    "OLLAMA_NUM_CTX",
    "WHISPER_MODEL",
    "WHISPER_NUM_THREADS",
    "FASTAPI_WORKERS",
    "RAG_TOP_K",
    "RAG_FETCH_K",
]

SNAPSHOT_FILENAME = ".machine_profile.json"

#: Default values used for keys that are inert on the active provider
#: (e.g. OLLAMA_MODEL on an MLX machine) — keeps the block uniform.
DEFAULT_MLX_MODEL = "mlx-community/Qwen2.5-14B-Instruct-4bit"
DEFAULT_MLX_EMBED_MODEL = "nomic-ai/nomic-embed-text-v1.5"
DEFAULT_OLLAMA_MODEL = "qwen2.5:7b-instruct-q3_K_M"


# ── Hardware detection (stdlib-only) ──────────────────────────────────

def _run(cmd: list[str]) -> str:
    """Run a command, return stripped stdout, or "" on any failure."""
    try:
        out = subprocess.run(
            cmd, capture_output=True, text=True, timeout=10,
        )
        return out.stdout.strip()
    except Exception:
        return ""


def _total_ram_gb() -> float | None:
    """System RAM in GB. psutil → POSIX sysconf → macOS sysctl → Windows ctypes."""
    try:
        import psutil
        return round(psutil.virtual_memory().total / (1024**3), 1)
    except Exception:
        pass
    if sys.platform == "darwin":
        raw = _run(["sysctl", "-n", "hw.memsize"])
        try:
            return round(int(raw) / (1024**3), 1)
        except ValueError:
            pass
    if hasattr(os, "sysconf"):
        try:
            pages, page_size = os.sysconf("SC_PHYS_PAGES"), os.sysconf("SC_PAGE_SIZE")
            if pages > 0 and page_size > 0:
                return round(pages * page_size / (1024**3), 1)
        except (ValueError, OSError):
            pass
    if sys.platform == "win32":
        try:
            import ctypes

            class _MEMORYSTATUSEX(ctypes.Structure):
                _fields_ = [
                    ("dwLength", ctypes.c_ulong), ("dwMemoryLoad", ctypes.c_ulong),
                    ("ullTotalPhys", ctypes.c_ulonglong), ("ullAvailPhys", ctypes.c_ulonglong),
                    ("ullTotalPageFile", ctypes.c_ulonglong), ("ullAvailPageFile", ctypes.c_ulonglong),
                    ("ullTotalVirtual", ctypes.c_ulonglong), ("ullAvailVirtual", ctypes.c_ulonglong),
                    ("ullAvailExtendedVirtual", ctypes.c_ulonglong),
                ]

            stat = _MEMORYSTATUSEX()
            stat.dwLength = ctypes.sizeof(_MEMORYSTATUSEX)
            if ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(stat)):
                return round(stat.ullTotalPhys / (1024**3), 1)
        except Exception:
            pass
    return None


def _nvidia_gpu() -> tuple[str, float] | None:
    """(gpu_name, vram_gb) from nvidia-smi, or None."""
    out = _run(["nvidia-smi", "--query-gpu=name,memory.total", "--format=csv,noheader"])
    if not out:
        return None
    line = out.splitlines()[0]
    parts = [p.strip() for p in line.split(",")]
    if len(parts) < 2:
        return None
    m = re.search(r"(\d+(?:\.\d+)?)\s*MiB", parts[1])
    if not m:
        return None
    return parts[0], round(int(m.group(1)) / 1024, 1)


def _mac_chip() -> str:
    """Chip name on Apple Silicon (e.g. 'Apple M3 Max'), else ''."""
    return (
        _run(["sysctl", "-n", "machdep.cpu.brand_string"])
        or _run(["sysctl", "-n", "hw.model"])
    )


def _is_container() -> bool:
    if os.environ.get("MACHINE_IN_CONTAINER") == "1":
        return True
    if sys.platform == "linux":
        try:
            cgroup = Path("/proc/1/cgroup").read_text()
            if any(t in cgroup for t in ("docker", "kubepods", "containerd")):
                return True
        except OSError:
            pass
        if Path("/run/.containerenv").exists():
            return True
    return False


def detect_hardware() -> dict:
    """
    Machine facts, stdlib-only. Never raises.

    Returns keys: os, arch, hostname, cpu_cores, ram_gb, device, platform,
    gpu_name, vram_gb, chip_tier, is_container, cloud.
    """
    system = _platform.system().lower()  # darwin / windows / linux
    arch = _platform.machine()
    cpu_cores = os.cpu_count() or 1
    ram_gb = _total_ram_gb()

    nv = _nvidia_gpu()
    chip = _mac_chip() if system == "darwin" else ""
    container = _is_container()

    if nv:
        device, platform, gpu_name, vram_gb = "cuda", "nvidia", nv[0], nv[1]
        chip_tier = nv[0]
    elif system == "darwin" and arch in ("arm64", "aarch64"):
        device, platform, gpu_name, vram_gb = "mps", "apple_silicon", chip, ram_gb
        chip_tier = chip
    elif system == "darwin":
        device, platform, gpu_name, vram_gb = "cpu", "intel_mac", chip, None
        chip_tier = chip
    else:
        device, platform, gpu_name, vram_gb = "cpu", "cpu", "", None
        chip_tier = ""

    cloud = (
        platform == "cpu"
        and system == "linux"
        and (container or os.environ.get("MACHINE_CLOUD") == "1" or Path("/etc/cloud").exists())
    )
    if cloud:
        platform = "cloud_linux"

    return {
        "os": system,
        "arch": arch,
        "hostname": socket.gethostname(),
        "cpu_cores": cpu_cores,
        "ram_gb": ram_gb,
        "device": device,
        "platform": platform,
        "gpu_name": gpu_name,
        "vram_gb": vram_gb,
        "chip_tier": chip_tier,
        "is_container": container,
        "cloud": cloud,
    }


# ── Sizing tiers ──────────────────────────────────────────────────────

def _clamp(n: int, cores: int) -> int:
    return max(1, min(n, cores)) if cores else max(1, n)


def _threads(spec: str, cores: int) -> int:
    """Thread specs: 'n' → min(n, cores); 'cores-2' → max(2, cores-2)."""
    if spec == "cores-2":
        return _clamp(max(2, cores - 2), cores)
    return _clamp(int(spec), cores)


# First match wins: platform must be listed AND mem_field in [min_mem, max_mem).
# mem_field is vram_gb for nvidia tiers, ram_gb everywhere else.
TIERS = [
    # ── Apple Silicon (unified memory) ──
    dict(tier_id="apple_high", label="Apple Silicon ≥32 GB", platforms=["apple_silicon"],
         min_mem=32.0, max_mem=float("inf"), mem_field="ram_gb",
         values=dict(LLM_PROVIDER="mlx", MLX_MODEL=DEFAULT_MLX_MODEL,
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL=DEFAULT_OLLAMA_MODEL,
                     OLLAMA_NUM_CTX="8192", WHISPER_MODEL="small.en",
                     WHISPER_NUM_THREADS="8", FASTAPI_WORKERS="4", RAG_TOP_K="5", RAG_FETCH_K="20")),
    dict(tier_id="apple_mid", label="Apple Silicon 16–31 GB", platforms=["apple_silicon"],
         min_mem=16.0, max_mem=32.0, mem_field="ram_gb",
         values=dict(LLM_PROVIDER="mlx", MLX_MODEL=DEFAULT_MLX_MODEL,
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL=DEFAULT_OLLAMA_MODEL,
                     OLLAMA_NUM_CTX="8192", WHISPER_MODEL="small.en",
                     WHISPER_NUM_THREADS="6", FASTAPI_WORKERS="3", RAG_TOP_K="5", RAG_FETCH_K="20")),
    dict(tier_id="apple_low", label="Apple Silicon 8–15 GB", platforms=["apple_silicon"],
         min_mem=8.0, max_mem=16.0, mem_field="ram_gb",
         warn="Tight 8–15 GB — 7B model, expect slower first token.",
         values=dict(LLM_PROVIDER="mlx", MLX_MODEL="mlx-community/Qwen2.5-7B-Instruct-4bit",
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL=DEFAULT_OLLAMA_MODEL,
                     OLLAMA_NUM_CTX="4096", WHISPER_MODEL="base.en",
                     WHISPER_NUM_THREADS="4", FASTAPI_WORKERS="2", RAG_TOP_K="4", RAG_FETCH_K="16")),
    # ── NVIDIA discrete GPU ──
    dict(tier_id="nvidia_high", label="NVIDIA ≥12 GB VRAM", platforms=["nvidia"],
         min_mem=12.0, max_mem=float("inf"), mem_field="vram_gb",
         values=dict(LLM_PROVIDER="ollama", MLX_MODEL=DEFAULT_MLX_MODEL,
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL="qwen2.5:14b",
                     OLLAMA_NUM_CTX="8192", WHISPER_MODEL="small.en",
                     WHISPER_NUM_THREADS="8", FASTAPI_WORKERS="4", RAG_TOP_K="5", RAG_FETCH_K="20")),
    dict(tier_id="nvidia_mid", label="NVIDIA 6–11 GB VRAM", platforms=["nvidia"],
         min_mem=6.0, max_mem=12.0, mem_field="vram_gb",
         values=dict(LLM_PROVIDER="ollama", MLX_MODEL=DEFAULT_MLX_MODEL,
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL=DEFAULT_OLLAMA_MODEL,
                     OLLAMA_NUM_CTX="4096", WHISPER_MODEL="small.en",
                     WHISPER_NUM_THREADS="4", FASTAPI_WORKERS="2", RAG_TOP_K="5", RAG_FETCH_K="20")),
    dict(tier_id="nvidia_low", label="NVIDIA <6 GB VRAM", platforms=["nvidia"],
         min_mem=0.0, max_mem=6.0, mem_field="vram_gb",
         warn="VRAM below budget (4 GB critical per memory_budget) — 3B model only.",
         values=dict(LLM_PROVIDER="ollama", MLX_MODEL=DEFAULT_MLX_MODEL,
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL="qwen2.5:3b",
                     OLLAMA_NUM_CTX="2048", WHISPER_MODEL="base.en",
                     WHISPER_NUM_THREADS="4", FASTAPI_WORKERS="2", RAG_TOP_K="3", RAG_FETCH_K="12")),
    # ── Intel Mac / CPU-only / cloud ──
    dict(tier_id="intel_mac", label="Intel Mac (Ollama Metal)", platforms=["intel_mac"],
         min_mem=0.0, max_mem=float("inf"), mem_field="ram_gb",
         values=dict(LLM_PROVIDER="ollama", MLX_MODEL=DEFAULT_MLX_MODEL,
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL=DEFAULT_OLLAMA_MODEL,
                     OLLAMA_NUM_CTX="4096", WHISPER_MODEL="small.en",
                     WHISPER_NUM_THREADS="4", FASTAPI_WORKERS="2", RAG_TOP_K="5", RAG_FETCH_K="20")),
    dict(tier_id="cpu_local", label="CPU-only (local)", platforms=["cpu"],
         min_mem=0.0, max_mem=float("inf"), mem_field="ram_gb",
         warn="CPU-only inference — expect slow responses.",
         values=dict(LLM_PROVIDER="ollama", MLX_MODEL=DEFAULT_MLX_MODEL,
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL=DEFAULT_OLLAMA_MODEL,
                     OLLAMA_NUM_CTX="4096", WHISPER_MODEL="base.en",
                     WHISPER_NUM_THREADS="cores-2", FASTAPI_WORKERS="2",
                     RAG_TOP_K="4", RAG_FETCH_K="16")),
    dict(tier_id="cloud_linux", label="Cloud / container Linux", platforms=["cloud_linux"],
         min_mem=0.0, max_mem=float("inf"), mem_field="ram_gb",
         warn="Container/cloud VM — consider a hosted LLM API; set OLLAMA_URL manually (outside the block).",
         values=dict(LLM_PROVIDER="ollama", MLX_MODEL=DEFAULT_MLX_MODEL,
                     MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL=DEFAULT_OLLAMA_MODEL,
                     OLLAMA_NUM_CTX="4096", WHISPER_MODEL="base.en",
                     WHISPER_NUM_THREADS="2", FASTAPI_WORKERS="2",
                     RAG_TOP_K="4", RAG_FETCH_K="16")),
]

#: Absolute fallback when no tier matches (should not happen — TIERS covers
#: every platform, but detect_hardware must never fail the deploy).
FALLBACK_TIER = dict(
    tier_id="cpu_local", label="CPU-only (fallback)", warn="Unmatched hardware — conservative defaults.",
    values=dict(LLM_PROVIDER="ollama", MLX_MODEL=DEFAULT_MLX_MODEL,
                MLX_EMBED_MODEL=DEFAULT_MLX_EMBED_MODEL, OLLAMA_MODEL=DEFAULT_OLLAMA_MODEL,
                OLLAMA_NUM_CTX="4096", WHISPER_MODEL="base.en",
                WHISPER_NUM_THREADS="2", FASTAPI_WORKERS="2", RAG_TOP_K="4", RAG_FETCH_K="16"),
)


def select_tier(hw: dict) -> dict:
    """
    Pick the sizing tier for the detected hardware. First TIERS entry whose
    platform matches and whose memory field falls in [min_mem, max_mem).

    Returns {tier_id, label, warn, values} with values covering every
    MANAGED_KEY; thread/worker counts clamped to the core count.
    """
    cores = hw.get("cpu_cores") or 1
    for t in TIERS:
        if hw.get("platform") not in t["platforms"]:
            continue
        mem = hw.get(t["mem_field"])
        if mem is None:
            continue  # unknown memory — keep scanning, fall back at the end
        if t["min_mem"] <= mem < t["max_mem"]:
            values = dict(t["values"])
            values["WHISPER_NUM_THREADS"] = str(_threads(values["WHISPER_NUM_THREADS"], cores))
            values["FASTAPI_WORKERS"] = str(_clamp(int(values["FASTAPI_WORKERS"]), cores))
            return {
                "tier_id": t["tier_id"],
                "label": t["label"],
                "warn": t.get("warn"),
                "values": values,
            }

    values = dict(FALLBACK_TIER["values"])
    values["WHISPER_NUM_THREADS"] = str(_threads(values["WHISPER_NUM_THREADS"], cores))
    values["FASTAPI_WORKERS"] = str(_clamp(int(values["FASTAPI_WORKERS"]), cores))
    return dict(tier_id=FALLBACK_TIER["tier_id"], label=FALLBACK_TIER["label"],
                warn=FALLBACK_TIER["warn"], values=values)


# ── .env block merge ──────────────────────────────────────────────────

def _read_env_text(env_path: Path) -> str:
    return env_path.read_text(encoding="utf-8", errors="replace")


def _newline_style(text: str) -> str:
    return "\r\n" if "\r\n" in text else "\n"


def _find_block(lines: list[str]) -> tuple[int, int] | None:
    """(start, end) line indices of the managed block, inclusive; None if absent."""
    start = end = None
    for i, line in enumerate(lines):
        if line.strip() == PROFILE_MARKER_OPEN:
            start = i
        elif line.strip() == PROFILE_MARKER_CLOSE and start is not None:
            end = i
            break
    if start is not None and end is not None:
        return start, end
    return None


def _key_value(line: str) -> tuple[str, str] | None:
    """Parse 'KEY=value' (leading whitespace tolerated). Returns None otherwise."""
    s = line.lstrip()
    if s.startswith("#") or "=" not in s:
        return None
    key, _, value = s.partition("=")
    return key.strip(), value.strip()


def _env_map(lines: list[str]) -> dict[str, str]:
    """First definition of each key wins (matches .env convention of one definition)."""
    out: dict[str, str] = {}
    for line in lines:
        kv = _key_value(line)
        if kv and kv[0] not in out:
            out[kv[0]] = kv[1]
    return out


def build_block(values: dict[str, str]) -> list[str]:
    """Marker-wrapped block lines for the given managed values."""
    lines = [PROFILE_MARKER_OPEN]
    lines += [f"{key}={values[key]}" for key in MANAGED_KEYS if key in values]
    lines.append(PROFILE_MARKER_CLOSE)
    return lines


def apply_profile(env_path, tier: dict, *, dry_run: bool = False, snapshot: dict | None = None) -> dict:
    """
    Merge the tier's values into .env, inside the managed block.

    Rules:
      - Lines outside the block are never modified except on first adoption.
      - First adoption (no snapshot yet): managed keys found outside the block
        are MOVED into it (action 'adopted'); a template-copied .env has no
        manual-override intent yet.
      - With a snapshot: managed keys outside the block are manual overrides
        → left untouched and omitted from the block ('manual-skip'); any stale
        copy inside the block is removed.
      - LLM_PROVIDER=auto is preserved verbatim on adoption (keeps portable
        provider auto-detection instead of pinning).
      - Idempotent: writes nothing when the result matches the file.

    Returns {changed, actions (per managed key), removed_from_block, new_content}.
    """
    path = Path(env_path)
    text = _read_env_text(path)
    nl = _newline_style(text)
    lines = text.splitlines()

    span = _find_block(lines)
    if span:
        start, end = span
        outside = lines[:start] + lines[end + 1:]
        block_lines = lines[start:end + 1]
    else:
        outside = lines[:]
        block_lines = []

    outside_map = _env_map(outside)
    block_map = _env_map(block_lines)

    actions: dict[str, str] = {}
    adopted_lines: list[str] = []   # full line texts moved from outside into the block
    new_block_values: dict[str, str] = {}
    removed_from_block: list[str] = []

    for key in MANAGED_KEYS:
        tier_value = str(tier["values"][key])
        outside_value = outside_map.get(key)

        if key in outside_map:
            if snapshot is None:
                # First adoption: the outside definition is a template leftover,
                # not a deliberate override — move it into the block.
                value = tier_value
                if key == "LLM_PROVIDER" and outside_value.lower() == "auto":
                    value = outside_value  # preserve portable auto-detection
                adopted_lines.append(key)
                actions[key] = "adopted"
            else:
                # Deliberate manual override — wins; drop any stale block copy.
                actions[key] = "manual-skip"
                if key in block_map:
                    removed_from_block.append(key)
                continue
        else:
            value = tier_value

        new_block_values[key] = value
        if key not in actions:
            # Only label when adoption didn't already do so.
            if key in block_map:
                actions[key] = "unchanged" if block_map[key] == value else "update"
            else:
                actions[key] = "insert"

    # Rebuild the file: outside (minus adopted key lines) + new block.
    kept_outside = [
        line for line in outside
        if not (_key_value(line) and _key_value(line)[0] in adopted_lines)
    ]
    block = build_block(new_block_values)

    new_lines = kept_outside
    # Normalize trailing blank lines before appending the block.
    while new_lines and new_lines[-1].strip() == "":
        new_lines.pop()
    new_lines += [""] + block
    new_text = nl.join(new_lines) + nl

    changed = new_text != text
    if not dry_run and changed:
        # Atomic write: temp file in the same directory + os.replace.
        tmp = path.with_name(path.name + ".tmp")
        tmp.write_text(new_text, encoding="utf-8")
        os.replace(tmp, path)

    return {
        "changed": changed,
        "actions": actions,
        "applied": new_block_values,  # actual values written into the block
        "removed_from_block": removed_from_block,
        "new_content": new_text if changed else None,
    }


# ── Snapshot sidecar ──────────────────────────────────────────────────

def get_snapshot_path(env_path=None) -> Path:
    """Snapshot lives next to .env (default: <repo_root>/.machine_profile.json)."""
    if env_path:
        return Path(env_path).resolve().parent / SNAPSHOT_FILENAME
    return Path(__file__).resolve().parent.parent / SNAPSHOT_FILENAME


def load_snapshot(env_path=None) -> dict | None:
    try:
        data = json.loads(get_snapshot_path(env_path).read_text(encoding="utf-8"))
        return data if isinstance(data, dict) else None
    except (OSError, ValueError):
        return None


def _profile_id(values: dict[str, str]) -> str:
    payload = json.dumps({k: values[k] for k in sorted(values)}, sort_keys=True)
    return hashlib.sha256(payload.encode()).hexdigest()[:12]


def write_snapshot(env_path, tier: dict, hw: dict, actions: dict, removed_from_block: list[str]) -> dict:
    """
    Persist .machine_profile.json next to .env. Returns the snapshot dict.
    """
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    applied = {k: str(v) for k, v in tier["values"].items()}
    snapshot = {
        "profile_id": _profile_id(applied),
        "created_at": now,
        "updated_at": now,
        "hostname": hw.get("hostname", ""),
        "detected": {
            "os": hw.get("os"), "arch": hw.get("arch"),
            "cpu_cores": hw.get("cpu_cores"), "ram_gb": hw.get("ram_gb"),
            "device": hw.get("device"), "platform": hw.get("platform"),
            "gpu_name": hw.get("gpu_name"), "vram_gb": hw.get("vram_gb"),
            "chip_tier": hw.get("chip_tier"), "is_container": hw.get("is_container"),
        },
        "tier_id": tier.get("tier_id"),
        "tier_label": tier.get("label"),
        "applied": applied,
        "manual_overrides": [k for k, a in actions.items() if a == "manual-skip"],
        "removed_from_block": list(removed_from_block),
    }
    prev = load_snapshot(env_path)
    if prev:
        snapshot["created_at"] = prev.get("created_at", now)
    get_snapshot_path(env_path).write_text(
        json.dumps(snapshot, indent=2) + "\n", encoding="utf-8",
    )
    return snapshot


# ── Drift self-check (startup) ────────────────────────────────────────

DRIFT_TOLERANCES = {
    # (field, tolerance): numeric comparisons use these bands to absorb
    # rounding and thermal noise; strings compare exactly.
    "ram_gb": 2.0,
    "vram_gb": 1.0,
    "cpu_cores": 2,
}


def check_drift(env_path=None) -> dict:
    """
    Compare the live machine against the profile snapshot .env was sized for.

    Returns {state, diffs, tier_id, hint} where state is one of:
      ok, drifted, no_profile, skipped_container, disabled.
    """
    if os.environ.get("MACHINE_PROFILE_CHECK") == "0":
        return {"state": "disabled", "diffs": [], "tier_id": None,
                "hint": "MACHINE_PROFILE_CHECK=0"}

    snapshot = load_snapshot(env_path)
    if snapshot is None:
        return {"state": "no_profile", "diffs": [], "tier_id": None,
                "hint": "Run: python scripts/predeploy.py"}

    hw = detect_hardware()
    if hw.get("is_container"):
        return {"state": "skipped_container", "diffs": [], "tier_id": snapshot.get("tier_id"),
                "hint": "Container — host snapshot not applicable"}

    s = snapshot.get("detected", {})
    diffs = []

    for field in ("platform", "device", "gpu_name"):
        if s.get(field) is not None and hw.get(field) != s.get(field):
            diffs.append({"key": field, "snapshot": s.get(field), "live": hw.get(field)})

    for field, tol in DRIFT_TOLERANCES.items():
        sv, lv = s.get(field), hw.get(field)
        if sv is not None and lv is not None and abs(float(lv) - float(sv)) > tol:
            diffs.append({"key": field, "snapshot": sv, "live": lv})

    if diffs:
        return {"state": "drifted", "diffs": diffs, "tier_id": snapshot.get("tier_id"),
                "hint": "Machine changed since config was sized — re-run: python scripts/predeploy.py"}

    return {"state": "ok", "diffs": [], "tier_id": snapshot.get("tier_id"), "hint": ""}
